apiVersion: apps/v1
kind: Deployment
metadata:
    name: platforms-depl
spec:
    replicas: 1
    selector:
        matchLabels:
            app: microservice
    template:
        metadata:
            labels:
                app: microservice
        spec:
            containers:
                - name: microservice
                  image: etozheslim/platformservice:latest